version: '3.9'
services:
  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ${SRC_PATH}:/python/src
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${HTTP_PORT_HOST}:80
    volumes:
      - ./nginx/sites:/etc/nginx/sites-available